import * as pdfjs from './vendor/pdf.min.mjs';
pdfjs.GlobalWorkerOptions.workerSrc = './vendor/pdf.worker.min.mjs';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db, projects=[], selected=null, editing=null, doc=null, page=1, renderVersion=0, drawVersion=0, tab='design', downloadUrl=null;
const urls=new Map(), statuses=['Реализовано','На стадии проекта','Не согласовано'];
const fmt=date=>!date?'Не указана':new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(date+'T12:00:00'));
const badge=s=>`<span class="badge ${s===statuses[1]?'progress':s===statuses[2]?'rejected':''}">${esc(s)}</span>`;
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('forma-project-library',1);r.onupgradeneeded=()=>r.result.createObjectStore('projects',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function records(){return new Promise((resolve,reject)=>{const tx=db.transaction('projects'),r=tx.objectStore('projects').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function put(p){return new Promise((resolve,reject)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(p);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function coverFor(blob){const pdf=await pdfjs.getDocument({data:new Uint8Array(await blob.arrayBuffer())}).promise;try{const p=await pdf.getPage(1),v=p.getViewport({scale:1.1}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return await new Promise(r=>c.toBlob(r,'image/png'));}finally{await pdf.destroy()}}
function demoPDF(name,color,index,assembly=false){
 const bg=['0.89 0.89 0.84','0.83 0.87 0.84','0.88 0.85 0.80','0.83 0.86 0.89','0.89 0.85 0.83','0.86 0.88 0.81'][index];
 const palette=[color,'0.94 0.93 0.86','0.26 0.34 0.29'];let stream=`${bg} rg 0 0 600 400 re f\n`;
 const poly=(pts,col)=>{stream+=`${col} rg ${pts[0]} ${pts[1]} m `;for(let i=2;i<pts.length;i+=2)stream+=`${pts[i]} ${pts[i+1]} l `;stream+='h f\n'};
 const line=(pts)=>{stream+='0.51 0.56 0.48 RG 0.5 w '+pts[0]+' '+pts[1]+' m ';for(let i=2;i<pts.length;i+=2)stream+=`${pts[i]} ${pts[i+1]} l `;stream+='S\n'};
 const box=(x,y,w,d,h,c)=>{poly([x,y,x+w,y+35,x+w+d,y+35-d*.55,x+d,y-d*.55],'0.71 0.72 0.65');poly([x,y,x+w,y+35,x+w,y+35+h,x,y+h],c);poly([x+w,y+35,x+w+d,y+35-d*.55,x+w+d,y+35-d*.55+h,x+w,y+35+h],palette[2]);poly([x,y+h,x+w,y+35+h,x+w+d,y+35-d*.55+h,x+d,y-d*.55+h],palette[1]);};
 if(assembly){stream='0.98 0.98 0.96 rg 0 0 600 400 re f\n';for(let x=40;x<580;x+=20)line([x,50,x,340]);for(let y=60;y<350;y+=20)line([30,y,570,y]);stream+='0.2 0.3 0.23 RG 2 w 100 110 370 165 re S 100 220 150 55 re S 300 110 65 70 re S 410 180 60 95 re S\n';line([90,95,480,95]);line([85,100,85,285]);}
 else{poly([68,126,339,208,551,90,273,18],'0.76 0.78 0.71');box(120,142,215,34,120,palette[0]);box(330,137,35,125,115,palette[0]);box(155,105,110,45,36,'0.92 0.91 0.84');box(324,66,60,30,44,palette[0]);if(index%2===0)box(230,153,22,25,146,palette[0]);for(let i=0;i<3;i++){stream+=`0.34 0.44 0.30 rg ${460+i*10} ${78+i*8} 8 44 re f\n`;}}
 stream+=`0.23 0.3 0.24 rg BT /F1 10 Tf 30 370 Td (${name.toUpperCase()}) Tj ET BT /F1 7 Tf 30 351 Td (${assembly?'INSTALLATION / PLAN':'DESIGN PROJECT / CONCEPT'} - DEMO) Tj ET BT /F1 7 Tf 30 20 Td (FORMA STUDIO / SAMPLE DOCUMENT) Tj ET\n`;
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 400] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}endstream`];let out='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(out.length);out+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=out.length;out+=`xref\n0 6\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([out],{type:'application/pdf'});
}
async function seed(){const rows=[['Выставочный стенд «Точка»','Сбер','ПМЭФ 2026','Анна Смирнова','2026-09-24',0,'SBER / POINT','0.32 0.49 0.34'],['Пространство новых идей','Яндекс','Технологическая конференция','Илья Волков','2026-09-12',1,'YANDEX / IDEAS','0.83 0.68 0.29'],['Павильон «Тёплый свет»','Самолёт','Арх Москва 2026','Мария Кузнецова','2026-08-20',0,'SAMOLET / LIGHT','0.65 0.54 0.42'],['Студия диалога','Сбер','Форум городской среды','Анна Смирнова','2026-07-18',2,'SBER / DIALOGUE','0.43 0.52 0.62'],['Выставочный стенд «Ритм»','МТС','Российская неделя дизайна','Дмитрий Орлов','2026-06-05',1,'MTS / RHYTHM','0.63 0.34 0.30'],['Зона деловых встреч','Самолёт','Форум недвижимости','Мария Кузнецова','2025-11-14',0,'SAMOLET / MEETING','0.44 0.48 0.33']];for(let i=0;i<rows.length;i++){const [title,customer,event,manager,date,status,name,color]=rows[i],design=demoPDF(name,color,i),assembly=demoPDF(name,color,i,true);await put({id:crypto.randomUUID(),title,customer,event,manager,date,status:statuses[status],source:'',design,assembly,cover:await coverFor(design),demo:true})}}
async function refresh(){projects=(await records()).sort((a,b)=>Number(!!b.model)-Number(!!a.model)||b.date.localeCompare(a.date));for(const url of urls.values())URL.revokeObjectURL(url);urls.clear();projects.forEach(p=>{if(p.cover)urls.set(p.id,URL.createObjectURL(p.cover))});const customer=$('#customer-filter').value,year=$('#year-filter').value;const customers=[...new Set(projects.map(p=>p.customer))].sort((a,b)=>a.localeCompare(b,'ru'));$('#customer-filter').innerHTML='<option value="">Все заказчики</option>'+customers.map(c=>`<option>${esc(c)}</option>`).join('');$('#customer-filter').value=customers.includes(customer)?customer:'';$('#customer-list').innerHTML=customers.map(c=>`<option value="${esc(c)}"></option>`).join('');const years=[...new Set(projects.map(p=>p.date.slice(0,4)).filter(Boolean))].sort().reverse();$('#year-filter').innerHTML='<option value="">Все годы</option>'+years.map(y=>`<option>${y}</option>`).join('');$('#year-filter').value=years.includes(year)?year:'';$('#total').textContent=String(projects.length).padStart(2,'0');$('#nav-count').textContent=projects.length;$('#done-count').textContent=String(projects.filter(p=>p.status===statuses[0]).length).padStart(2,'0');$('#progress-count').textContent=String(projects.filter(p=>p.status===statuses[1]).length).padStart(2,'0');$('#clients-count').textContent=String(customers.filter(c=>c!=='Не указан').length).padStart(2,'0');render()}
function render(){renderSidebar();const q=$('#search').value.trim().toLocaleLowerCase('ru');const filtered=projects.filter(p=>(!q||[p.title,p.customer,p.event,p.manager].some(v=>v.toLocaleLowerCase('ru').includes(q)))&&(!$('#customer-filter').value||p.customer===$('#customer-filter').value)&&(!$('#status-filter').value||p.status===$('#status-filter').value)&&(!$('#year-filter').value||p.date.startsWith($('#year-filter').value)));$('#result-count').textContent=`Показано ${filtered.length} из ${projects.length}`;$('#grid').innerHTML=filtered.length?filtered.map(p=>`<button class="card" data-id="${p.id}" aria-label="Открыть проект ${esc(p.title)}"><div class="cover">${urls.has(p.id)?`<img src="${urls.get(p.id)}" alt="${p.model&&!p.design?'Превью модели Fusion':'Первая страница дизайн-проекта'}" loading="lazy">`:'<span class="no-cover">Добавьте дизайн-проект</span>'}<span class="cover-count">${p.model?'3D · ':''}${Number(!!p.design)+Number(!!p.assembly)} PDF</span></div><div class="card-content"><div class="card-kicker"><span class="customer">${esc(p.customer)}</span>${badge(p.status)}</div><h2>${esc(p.title)}</h2><p>${esc(p.event)||'Мероприятие не указано'}</p><div class="card-bottom"><span>${esc(p.manager)||'Менеджер не указан'}</span><span>${fmt(p.date)}</span></div></div></button>`).join(''):'<div class="empty"><h2>Проекты не найдены</h2><p>Измените фильтры или добавьте новый проект.</p></div>';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openProject(c.dataset.id))}
async function openProject(id){selected=projects.find(p=>p.id===id);tab=selected.model?'model':'design';const p=selected;$('#drawer-content').innerHTML=`<h2>${esc(p.title)}</h2>${badge(p.status)}<dl class="details"><div><dt>Заказчик</dt><dd>${esc(p.customer)}</dd></div><div><dt>Дата создания</dt><dd>${fmt(p.date)}</dd></div><div><dt>Мероприятие</dt><dd>${esc(p.event)||'—'}</dd></div><div><dt>Менеджер компании</dt><dd>${esc(p.manager)||'—'}</dd></div></dl><div class="tabs"><button class="tab ${tab==='design'?'selected':''}" data-tab="design">Дизайн-проект</button><button class="tab" data-tab="assembly">Монтажная схема</button>${p.model?'<button class="tab selected" data-tab="model">3D-модель</button>':''}</div><div id="pdf-area"></div>${p.source?`<a class="source-link" href="${esc(p.source)}" target="_blank" rel="noopener noreferrer"><span><strong>Исходники проекта</strong><small>Открыть на Яндекс Диске</small></span><span>↗</span></a>`:'<div class="source-link"><span><strong>Исходники проекта</strong><small>Ссылка на Яндекс Диск пока не добавлена</small></span></div>'}<div class="drawer-actions"><button class="quiet" id="edit-btn">Редактировать проект</button></div>`;if(!$('#drawer').open)$('#drawer').showModal();document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{tab=t.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('selected',x===t));loadPDF()});$('#edit-btn').onclick=()=>{$('#drawer').close();openEditor(p.id)};await loadPDF()}
async function loadPDF(){const version=++renderVersion;++drawVersion;const old=doc;doc=null;if(old)await old.destroy();if(version!==renderVersion)return;if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=null;if(tab==='model'&&selected?.model){$('#pdf-area').innerHTML='<iframe class="model-frame" src="viewer.html?v=selection-2" title="3D-модель проекта" allow="fullscreen" allowfullscreen></iframe><p class="model-note">Модель из Fusion · v23. Структура компонентов восстановлена. Для работы с деталями разверните просмотрщик.</p>';return;}const blob=selected?.[tab];if(!blob){$('#pdf-area').innerHTML='<div class="empty-file">PDF пока не добавлен. Загрузите его в настройках проекта.</div>';return;}$('#pdf-area').innerHTML='<div class="empty-file">Открываем документ…</div>';try{const loaded=await pdfjs.getDocument({data:new Uint8Array(await blob.arrayBuffer())}).promise;if(version!==renderVersion){await loaded.destroy();return;}doc=loaded;page=1;downloadUrl=URL.createObjectURL(blob);$('#pdf-area').innerHTML=`<div class="pdf-toolbar"><button id="prev-page" aria-label="Предыдущая страница">←</button><span id="page-number"></span><button id="next-page" aria-label="Следующая страница">→</button><a href="${downloadUrl}" download="${esc(selected.title)} — ${tab==='design'?'дизайн-проект':'монтажная схема'}.pdf">Скачать PDF ↓</a></div><div class="pdf-viewer" id="canvas-host"></div>`;$('#prev-page').onclick=()=>{if(page>1){page--;drawPage()}};$('#next-page').onclick=()=>{if(page<doc.numPages){page++;drawPage()}};await drawPage();}catch(e){if(version===renderVersion)$('#pdf-area').innerHTML='<div class="empty-file">Не удалось открыть PDF. Возможно, он повреждён или защищён паролем.</div>';}}
async function drawPage(){const version=++drawVersion,current=doc;if(!current)return;const n=page;$('#page-number').textContent=`${n} / ${current.numPages}`;$('#prev-page').disabled=n===1;$('#next-page').disabled=n===current.numPages;const p=await current.getPage(n);if(version!==drawVersion)return;const v=p.getViewport({scale:1.8}),canvas=document.createElement('canvas');canvas.width=v.width;canvas.height=v.height;try{await p.render({canvasContext:canvas.getContext('2d'),viewport:v}).promise;if(version===drawVersion)$('#canvas-host')?.replaceChildren(canvas);}catch{}}
function openEditor(id){editing=id?projects.find(p=>p.id===id):null;const form=$('#project-form');form.reset();$('#form-error').textContent='';$('#editor-title').textContent=editing?'Редактирование проекта':'Новый проект';const now=new Date();form.elements.date.value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;if(editing)for(const key of ['title','customer','event','manager','date','status','source'])form.elements[key].value=editing[key];$('#editor').showModal()}
$('#project-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=$('#save-btn');button.disabled=true;button.textContent='Сохраняем…';$('#form-error').textContent='';try{const data=new FormData(form),p={...(editing||{id:crypto.randomUUID(),demo:false})};for(const k of ['title','customer','event','manager','date','status','source'])p[k]=String(data.get(k)).trim();if(!p.title||!p.customer)throw Error('Укажите название проекта и заказчика.');if(p.source){const u=new URL(p.source);if(u.protocol!=='https:'||!['disk.yandex.ru','disk.yandex.com','yadi.sk'].includes(u.hostname))throw Error('Укажите HTTPS-ссылку на Яндекс Диск.');}for(const kind of ['design','assembly']){const f=data.get(kind);if(f?.size){if(f.size>50*1024*1024)throw Error('PDF должен быть не больше 50 МБ.');if(await f.slice(0,5).text()!=='%PDF-')throw Error('Выберите корректный файл PDF.');const cover=await coverFor(f);p[kind]=f;if(kind==='design')p.cover=cover;}}await put(p);await refresh();$('#editor').close();toast('Проект сохранён в этом браузере');}catch(e){$('#form-error').textContent=e.name==='QuotaExceededError'?'Недостаточно места в браузере для сохранения файлов.':e.message||'Не удалось сохранить проект.';}finally{button.disabled=false;button.textContent='Сохранить проект'}};
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));$('#drawer').addEventListener('close',()=>{document.querySelector('.model-frame')?.remove();++renderVersion;++drawVersion;if(doc){doc.destroy();doc=null;}if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null;}});$('#add-btn').onclick=()=>openEditor();$('#invite-btn').onclick=()=>$('#invite-modal').showModal();['search','customer-filter','status-filter','year-filter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#all-nav').onclick=()=>{$('#search').value='';['customer-filter','status-filter','year-filter'].forEach(id=>$('#'+id).value='');render()};$('#clients-nav').onclick=()=>{$('#customer-filter').focus();$('#customer-filter').showPicker?.()};
try{db=await openDB();if(!(await records()).length)await seed();await addHealthModel();await refresh();}catch(e){$('#grid').innerHTML='<div class="empty"><h2>Не удалось открыть локальную библиотеку</h2><p>Разрешите хранение данных в браузере и обновите страницу.</p></div>';console.error(e)}

function renderSidebar(){
 const total=projects.length,done=projects.filter(p=>p.status===statuses[0]).length;
 const percent=total?Math.round(done/total*100):0;
 $('#side-total').textContent=String(total).padStart(2,'0');
 $('#side-customers').textContent=new Set(projects.map(p=>p.customer).filter(c=>c!=='Не указан')).size;
 $('#side-percent').textContent=percent+'%';
 $('#side-progress').style.width=percent+'%';
 $('#side-statuses').innerHTML=[...statuses,...(projects.some(p=>p.status==='Не указан')?['Не указан']:[])].map((status,i)=>`<button class="side-status" data-summary-status="${esc(status)}" aria-pressed="${$('#status-filter').value===status}"><i class="dot ${['green','amber','rose','neutral'][i]}"></i><span>${esc(status)}</span><strong>${projects.filter(p=>p.status===status).length}</strong></button>`).join('');
 document.querySelectorAll('[data-summary-status]').forEach(button=>button.onclick=()=>{
   $('#search').value='';$('#customer-filter').value='';$('#year-filter').value='';
   $('#status-filter').value=button.dataset.summaryStatus;render();
 });
}

async function addHealthModel(){
 const id='health-territory-v23';if((await records()).some(p=>p.id===id))return;
 const response=await fetch('./models/health-territory-v23.png');if(!response.ok)throw Error('Не загружена обложка 3D-модели');
 await put({id,title:'Территория здоровья · v23',customer:'Не указан',event:'',manager:'',date:'',status:'Не указан',source:'',model:'health-territory-v23',cover:await response.blob(),demo:false});
}
